
from django.db import models
from django.utils import timezone
from Authentication.models import *
from django.core.exceptions import ValidationError

# Create your models here.
# here are the databases that we are going to use for the website

class News(models.Model): # if not specified a primary key is explicitly generated by django migrations
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=False,default="")
    content = models.TextField(blank=False,default="")
    category = models.CharField(max_length=50)
    Image = models.TextField(default="https://th.bing.com/th/id/R.daa7359bb5a739976f49f73a13248445?rik=96%2fTS%2buS%2fKFAyA&pid=ImgRaw&r=0")
    date_uploaded = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title
    

class Game(models.Model):
    id = models.IntegerField(primary_key=True)
    Against = models.CharField(max_length=100)
    AgaistTeamLogo = models.TextField() # I added this for the sake of design
    location = models.CharField(max_length=100,default="Red Bull Arena") # note that red bull arena is the home stadium for leipzig
    date = models.DateTimeField(blank=False)
    type = models.TextField() # I do not know what this means, but it is the database design so I added it 

class Field(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price_per_hour = models.DecimalField(max_digits=5, decimal_places=2)
    image = models.ImageField(upload_to='fields/',default='fields/stadium1.jpg')

    def __str__(self):
        return self.name

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    
        
    def __str__(self):
        return f"{self.field.name} booked by {self.user.username} on {self.date}"





