
from django.db import models
from django.utils import timezone
from Authentication.models import *

# Create your models here.
# here are the databases that we are going to use for the website

class News(models.Model): # if not specified a primary key is explicitly generated by django migrations
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=False,default="")
    content = models.TextField(blank=False,default="")
    category = models.CharField(max_length=50)
    Image = models.TextField(default="https://th.bing.com/th/id/R.daa7359bb5a739976f49f73a13248445?rik=96%2fTS%2buS%2fKFAyA&pid=ImgRaw&r=0")
    date_uploaded = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title
    

class Game(models.Model):
    id = models.IntegerField(primary_key=True)
    Against = models.CharField(max_length=100)
    AgaistTeamLogo = models.TextField() # I added this for the sake of design
    location = models.CharField(max_length=100,default="Red Bull Arena") # note that red bull arena is the home stadium for leipzig
    date = models.DateTimeField(blank=False)
    type = models.TextField() # I do not know what this means, but it is the database design so I added it 





