# Generated by Django 5.0.2 on 2024-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_field_image_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='image',
            field=models.URLField(default='https://editorial.uefa.com/resources/0287-198ec548cd8e-23ee610c0bb8-1000/rb_leipzig_v_manchester_city_round_of_16_leg_one_-_uefa_champions_league_5_.jpeg'),
        ),
    ]
