# Generated by Django 5.0.2 on 2024-04-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldsBooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='SoccerField',
        ),
    ]
