# Generated by Django 5.0.2 on 2024-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FieldsBooking', '0002_field_delete_soccerfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='image',
            field=models.ImageField(default='fields/default.jpg', upload_to='fields/'),
        ),
    ]
